### ISSUE TITLE
#Issue [email-verification]: Sending verification email when registering a new user does not work

### ISSUE THREAD

**Issue by deanone** [eclipse-researchlabs/smartclide-ide-front-end#10]
I tried to register a new user into the SmartCLIDE IDE Eclipse Che workspace (see the attached figure), but I am not receiving the email with the verification link no matter what. 

I tried multiple times to have the verification resend back to me, but to no avail. I also checked in my spam folder, but the email was not there either.

Can you please check? User registration in the SmartCLIDE IDE is one of the very first steps we will need soon to demonstrate.
![smartclide-ide-registration-page](https://user-images.githubusercontent.com/5978626/189615744-60fd94ab-7c04-4568-863b-15ca82e3c2d0.png)

**Comment by goncalorolo** [comment]
We already had this issue in the beginning of the project and, as far as I can recall, it was related with some configuration in the Che Server side. @philipreimer, can you take a look at this?

**Comment by deanone** [comment]
Oh ok, let's see what @philipreimer can tell us about that then.

**Comment by philipreimer** [comment]
We are looking into it.

**Comment by deanone** [comment]
Thanks @philipreimer

**Comment by philipreimer** [comment]
The issue should be resolved now. Please test, and re-open this issue if you still experience any problems.

**Comment by deanone** [comment]
Yes, it works now @philipreimer. I just checked. Thanks
