### ISSUE TITLE
Service creation flow blocks by problem on GitLab API

### ISSUE THREAD

**Issue by deanone** [eclipse-researchlabs/smartclide-ide-front-end#12]
Dear @goncalorolo ,

I have tried to create a new service in our platform after your new release. 

I provide all the required information, and when I try to add the service there is an issue that says "Problem with GitLab api" (see attached figure).

![gitlab_api_issue](https://user-images.githubusercontent.com/5978626/190915921-eba20656-eb5f-46d6-ba18-b7a3fe9cc52c.png)

I have provided my personal credentials for GitLab. In particular, I put:

- Type: GitLab
- URL: <My GitLab path> (https://gitlab.com/deanone)
- Username: My GitLab username (deanone)
- Token: My GitLab password

The process stops there, and no service is created.

Can you please check it?

Thanks

**Comment by deanone** [comment]
Good morning @goncalorolo. Any updates on this?

**Comment by goncalorolo** [comment]
Hi, @deanone.

From what you've described, it seems that the only problem is the URL provided in the GitLab credentials. It is not expected to include the username there. The value should simply be https://gitlab.com.

**Comment by deanone** [comment]
Hi, @goncalorolo .

No, the issue remains.

I put:
Type: GitLab
URL: https://gitlab.com
Username: asal@iti.gr (my main email on GitLab) or deanone (my username) - I tried them both
Token: my GitLab password

I still receive the same "Problem with GitLab api" error. I have tried it in both Firefox and Chrome, and its the same every time.

Have you tried it with any of your GitLab or GitHub accounts?

**Comment by goncalorolo** [comment]
I think that the service-creation API is expecting an actual token for authentication, not the password of your account. Also, I have always used my username instead of the email.

**Comment by deanone** [comment]
So, I need to provide a PAT (personal access token) instead of a password? Ok, let me test it and I'll come back to you.

**Comment by deanone** [comment]
@goncalorolo I managed to overcome the issue by creating a new token in GitLab and providing this to the Token field.

Hence, I close this issue.
