### ISSUE TITLE
Renaming of field 'Token' in Gredentials page of user's profile

### ISSUE THREAD

**Issue by deanone** [eclipse-researchlabs/smartclide-ide-front-end#14]
Dear @goncalorolo,

I think that it would be better to rename the field "Token" of the "Edit Git Credentials" form (My Account -> Credentials -> Pencil icon to edit existing Git credentials or + icon to add new Git credentials) to "Personal Access Token (PAT)".

I think it would be more clear this way. What do you think?

**Comment by goncalorolo** [comment]
I have renamed the field to Personal Access Token (PAT) in both (add and edit) Git credentials' forms, as suggested.

**Comment by deanone** [comment]
Thank you @goncalorolo.
