### ISSUE TITLE
Service creation issue

### ISSUE THREAD

**Issue by deanone** [eclipse-researchlabs/smartclide-ide-front-end#15]
Dear @nikosnikolaidis ,

I am trying to create a new Node service through our platform. When I am at the final stage, and after I have put all the necessary information, I click "Add", and the following error appears

![screenshot_service_creation_node](https://user-images.githubusercontent.com/5978626/191200392-7bf6cff5-49ec-4093-b337-b5d9a7d4534a.png)

"Service Creation had an error and GitLab repository deletion failed"

The weird think though is that the project is created on my GitLab, but it is not stored in our database. I mean, when I call the corresponding endpoint of the SmartCLIDE DB API to get my services, I get an empty array.

So, it seems that the service creation process breaks at some point and does not finish correctly.

Can you please check it?

Thanks.

Best,

Athanasios

**Comment by deanone** [comment]
@nikosnikolaidis see also this screenshot (from Chrome)

![screenshot_service_creation_node_2](https://user-images.githubusercontent.com/5978626/191205317-9f8a3681-c57c-4dc3-b56b-d12375c1d066.png)

**Comment by goncalorolo** [comment]
Weird... Those errors have never happened to me. What I can say is that those logs are not from the frontend...

Are your credentials still valid, @deanone?

**Comment by deanone** [comment]
> Weird... Those errors have never happened to me. What I can say is that those logs are not from the frontend... In fact, they seem to be coming from the service-creation backend.
> 
> Are your credentials still valid, @deanone?

@goncalorolo Yes they are. In fact, I have updated my credentials in my SmartCLIDE profile (just in case) before proceeding with the service creation process.

Yes, I also thought that the problem arises from the service-creation backend service. I am waiting for @nikosnikolaidis response on this.

**Comment by nikosnikolaidis** [comment]
This error is due to the space in the name provided to the service.
We could change it and copy the logic of GitLab, in order to add a dash (-) in every space, in the backend service or in the frontend.

**Comment by deanone** [comment]
Ok, @nikosnikolaidis so if I put in the name something like "Node service" right now I will trigger this error. Hence, I have to use "Node-service", right? In that case, (for the next release) we need to put something like a form validation that will inform the user that the service name should be dash-separated. @goncalorolo wdyt?

**Comment by deanone** [comment]
Yes, that would be great @goncalorolo. You can put it in the list of the upcoming updates for the next release!
