### ISSUE TITLE
hard-coded keycloak URL in user profile page

### ISSUE THREAD

**Issue by reimer-atb** [eclipse-researchlabs/smartclide-ide-front-end#54]
`MyAccount/Profile.vue` uses a hard-coded URL to keycloak. This prevents us from using the frontend with a different keycloak server.

**Comment by goncalorolo** [comment]
> Does meteor include the original `keycloak.json` in the bundled javascript? And when Profile.vue call `getKeycloakPageURL` it reads the URL from that javascript bundle, and not from the actual file `/opt/bundle/bundle/programs/web.browser/app/keycloak.json`?

Yes, that seems to be the case. For instantiating the Keycloak client in the frontend, we use Meteor's HTTP server to make the configuration file available. During the build process, however, Meteor makes some optimisations and we cannot change it afterwards. With that in mind, I think that this is only achievable if the configuration file is available at some URL. Do you know if Keycloak provides such a thing?

In any case, we have identified a possible solution. However, it will require some changes on our side that will take some time. In any case, we will try to get back to you as soon as possible.

**Comment by goncalorolo** [comment]
@philipreimer, I have made a change according to your description. Can you check #59 so I can make a new release for you to test?

**Comment by goncalorolo** [comment]
Thank you. The new image is available.
